name: compile scss

on:
  push:
    branches:
      - main
    paths:
      - "extended-default.scss"
      - ".github/workflows/ci.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Mkdir for compile
        run: mkdir -vp /tmp/extended-default/css
      - name: Compile SCSS to CSS
        uses: gha-utilities/sass-build@v0.4.8
        with:
          source: ./extended-default.scss
          destination: /tmp/extended-default/css/extended-default.css
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          ref: release
      - name: Add compiled file
        run: |
            mv /tmp/extended-default/css/extended-default.css ./
            git config user.name = "github-actions"
            git config user.email = "github-actions[bot]@users.noreply.github.com"
            ls
            git add ./extended-default.css
            git commit -m ":robot: Add compilet file"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release
